### PR TITLE
Redirect /owner/repo/pages to /owner/repo/pages/

### LINKED ISSUE #27: plugin cannot load css file
image
I put my static website on branch gb-pages.
And I access http://ip:port/test/pages
image
Am I put wrong path?

### PR DESCRIPTION
**Pull request by yaroot**
fixes #27

### CODE REVIEW

**Comment by yaroot** [comment]
@takezoe 

I found something weird

`/:owner/:repository/pages/*` would match `/root/foo/pages/bar/` but `params("splash")` would return `"bar"`, I expect `"bar/"`

Also if I have both routes 

```
get("/:owner/:repository/pages/") {} // this will match nothing
get("/:owner/:repository/pages") {} // this will match with or without trailing slash
```

**Comment by takezoe** [comment]
> `/:owner/:repository/pages/*` would match `/root/foo/pages/bar/` but `params("splash")` would return `"bar"`, I expect `"bar/"`, the servlet path would be `"/root/foo/pages/bar/"` though.

Maybe `params("splat")`? This returns a head element of slash-split `*` part. So, `"bar"` is expected in this case.

```
get("/:owner/:repository/pages") {} // this will match with or without trailing slash
```

This is expected, but I'm not sure why the following one doesn't match anything. Need to look into Scalatra codebase.

```
get("/:owner/:repository/pages/") {} // won't match anything
```

**Comment by yaroot** [comment]
> Maybe `params("splat")`?

typo sorry, it's splat. I don't know scalatra well, but this from the document the behavior is weird.

```
scala> import org.scalatra.SinatraPathPatternParser
import org.scalatra.SinatraPathPatternParser

scala> SinatraPathPatternParser("/:owner/:repo/pages/*")("/foo/bar/pages/baz/")
val res0: Option[org.scalatra.MultiParams] = Some(Map(owner -> Vector(foo), repo -> Vector(bar), splat -> Vector(baz/)))

scala> SinatraPathPatternParser("/:owner/:repo/pages/")("/foo/bar/pages")
val res1: Option[org.scalatra.MultiParams] = None

scala> SinatraPathPatternParser("/:owner/:repo/pages/")("/foo/bar/pages/")
val res2: Option[org.scalatra.MultiParams] = Some(Map(owner -> Vector(foo), repo -> Vector(bar)))

scala> SinatraPathPatternParser("/:owner/:repo/pages")("/foo/bar/pages")
val res3: Option[org.scalatra.MultiParams] = Some(Map(owner -> Vector(foo), repo -> Vector(bar)))

scala> SinatraPathPatternParser("/:owner/:repo/pages")("/foo/bar/pages/")
val res4: Option[org.scalatra.MultiParams] = None
```

**Comment by takezoe** [comment]
Hm, I see. We might have to fix the doc. Though I'm also not really sure about the core part of Scalatra because it has a long history including some inconsistencies, basically, we should respect the current behavior for the backward compatibility in applications currently use Scalatra. I will confirm the current behavior and will fix the doc to follow it.

**Comment by takezoe** [comment]
Ah, GitBucket automatically drops a tail slash.
https://github.com/gitbucket/gitbucket/blob/65afbd25b8f3d9e5b783d11f67f8ab964b1474e3/src/main/scala/gitbucket/core/controller/ControllerBase.scala#L53-L60

This change was introduced for matching a tail slash to all existing routes without changing anything.
https://github.com/gitbucket/gitbucket/pull/604

**Comment by yaroot** [comment]
For relative urls to work (at least for autoindex (index.html)) we need the trailing slash. Maybe the original path should be kept somewhere, or we could just use the servlet path from the request object.

**Comment by takezoe** [comment]
Yeah, there is a workaround.

1. Check the request path inside the action
2. Redirect with a tail slash if the request path doesn't end with slash

**Comment by yaroot** [comment]
This should work

**Review by takezoe — APPROVED** [review]
Yeah, looks good!

**Comment by takezoe** [comment]
I confirmed this works fine. Thank you for the fix!

**Pull request merged**
